version: '3.8'

services:
  document-service-mongo:
    image: mongo
    container_name: document-service-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./document-service-mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    restart: always